version: "3"
services:
  app:
    image: node:16.14-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    working_dir: /app
    command: yarn serve
  express:
    image: node:16.14-alpine
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    volumes:
      - ./express:/express
    working_dir: /express
    command: npm start
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  web:
    image: nginx:1.21.4
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
